export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/3CxUndGhUcZdt1Zggjdb2HkLLQX.jpg",
    genre_ids: [28, 12, 878],
    id: 640146,
    original_language: "en",
    original_title: "Ant-Man and the Wasp: Quantumania",
    overview:
      "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
    popularity: 3140.012,
    poster_path: "/A7SobaUTvb6d5Z3dpOhFxPG0RQf.jpg",
    release_date: "2023-02-15",
    title: "Ant-Man and the Wasp: Quantumania",
    video: false,
    vote_average: 4.5,
    vote_count: 2555,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/xnAi4BRoO3ZQ3wwxGn6UNoxQzDq.jpg",
    id: 823999,
    title: "Diabolik - Ginko Attacks",
    original_language: "it",
    original_title: "Diabolik - Ginko all'attacco!",
    overview:
      "Diabolik nearly gets caught in Inspector Ginko's latest trap, leaving his partner in crime Eva Kant behind in the escape. Furious, Eva offers Ginko her help in capturing the King of Terror, but the former has to face the return of an old flame of his.",
    poster_path: "/8QVbWBv94BAT9u1q9uJccwOxMzt.jpg",
    media_type: "movie",
    genre_ids: [80, 28],
    popularity: 129.252,
    release_date: "2022-11-17",
    video: false,
    vote_average: 5.94,
    vote_count: 250,
  },
  {
    adult: false,
    backdrop_path: "/9EIUIgBYzGra7Xxemgs8JB049si.jpg",
    id: 676841,
    title: "Unhappily Ever After",
    original_language: "es",
    original_title: "Infelices para Siempre",
    overview:
      "María José and Alfredo are about to celebrate their 20th anniversary and their children give them a trip to the hotel where they celebrated their honeymoon, but a spell will make them repeat the same day.",
    poster_path: "/qiAM7Y8xF8wJDDsjeSuLgzyFGmd.jpg",
    media_type: "movie",
    genre_ids: [35, 10749],
    popularity: 161.841,
    release_date: "2023-01-26",
    video: false,
    vote_average: 6.985,
    vote_count: 136,
  },
  {
    adult: false,
    backdrop_path: "/b9UCfDzwiWw7mIFsIQR9ZJUeh7q.jpg",
    id: 868759,
    title: "Ghosted",
    original_language: "en",
    original_title: "Ghosted",
    overview:
      "Salt-of-the-earth Cole falls head over heels for enigmatic Sadie — but then makes the shocking discovery that she’s a secret agent. Before they can decide on a second date, Cole and Sadie are swept away on an international adventure to save the world.",
    poster_path: "/liLN69YgoovHVgmlHJ876PKi5Yi.jpg",
    media_type: "movie",
    genre_ids: [28, 35, 10749],
    popularity: 1515.705,
    release_date: "2023-04-18",
    video: false,
    vote_average: 7.049,
    vote_count: 793,
  },
  {
    adult: false,
    backdrop_path: "/cL0cdccOMzM508ODsWPfHVMMAzo.jpg",
    id: 267805,
    title: "There Are No Saints",
    original_language: "en",
    original_title: "There Are No Saints",
    overview:
      "A man is imprisoned for a crime he didn't commit. When his wife is murdered and his son kidnapped and taken to Mexico, he devises an elaborate and dangerous plan to rescue his son and avenge the murder.",
    poster_path: "/fcOTYArjKuAgufwHoTvx8w9UKCv.jpg",
    media_type: "movie",
    genre_ids: [28, 9648, 53],
    popularity: 90.039,
    release_date: "2022-05-27",
    video: false,
    vote_average: 5.3,
    vote_count: 89,
  },
  {
    adult: false,
    backdrop_path: "/g8Yytnby0hIPft5l56mgJtZyR1k.jpg",
    id: 965839,
    title: "Lord of the Streets",
    original_language: "en",
    original_title: "Lord of the Streets",
    overview:
      "When Jason Dyson refuses to make his prized fighter throw an MMA match, a notorious gangster collects his debt by killing the fighter and kidnapping Jason's daughter. Now he must train a prisoner to endure five consecutive underground fights to save her.",
    poster_path: "/n9YWVQRc0zw0nwrFcOkOpffZxjc.jpg",
    media_type: "movie",
    genre_ids: [28],
    popularity: 108.552,
    release_date: "2022-04-22",
    video: false,
    vote_average: 5.238,
    vote_count: 63,
  },
  {
    adult: false,
    backdrop_path: "/eNJhWy7xFzR74SYaSJHqJZuroDm.jpg",
    id: 1033219,
    title: "Attack on Titan",
    original_language: "en",
    original_title: "Attack on Titan",
    overview:
      "As viable water is depleted on Earth, a mission is sent to Saturn's moon Titan to retrieve sustainable H2O reserves from its alien inhabitants. But just as the humans acquire the precious resource, they are attacked by Titan rebels, who don't trust that the Earthlings will leave in peace.",
    poster_path: "/qNz4l8UgTkD8rlqiKZ556pCJ9iO.jpg",
    media_type: "movie",
    genre_ids: [28, 878],
    popularity: 315.252,
    release_date: "2022-09-30",
    video: false,
    vote_average: 5.965,
    vote_count: 128,
  },
  {
    adult: false,
    backdrop_path: "/fTLMsF3IVLMcpNqIqJRweGvVwtX.jpg",
    id: 1035806,
    title: "Detective Knight: Independence",
    original_language: "en",
    original_title: "Detective Knight: Independence",
    overview:
      "Detective James Knight 's last-minute assignment to the Independence Day shift turns into a race to stop an unbalanced ambulance EMT from imperiling the city's festivities. The misguided vigilante, playing cop with a stolen gun and uniform, has a bank vault full of reasons to put on his own fireworks show... one that will strike dangerously close to Knight's home.",
    poster_path: "/jrPKVQGjc3YZXm07OYMriIB47HM.jpg",
    media_type: "movie",
    genre_ids: [28, 80, 53],
    popularity: 107.985,
    release_date: "2023-01-20",
    video: false,
    vote_average: 5.509,
    vote_count: 117,
  },
  {
    adult: false,
    backdrop_path: "/tFaC1Fb1sv1dALB0i9Avi76MHmn.jpg",
    id: 946310,
    title: "Pirates Down the Street II: The Ninjas from Across",
    original_language: "nl",
    original_title: "De Piraten van Hiernaast II: De Ninja's van de Overkant",
    overview:
      "The pirates feel right at home in Sandborough, but the atmosphere cools right down when the ninjas come to live in the street. After all, pirates and ninjas are sworn enemies!  While pirate captain Hector Blunderbuss struggles to get rid of his new neighbours, son Billy and ninja daughter Yuka become friends. The pirates challenge the ninjas to the ultimate battle at the village's annual hexathlon. Who will win the match? Ninjas are faster and more agile of course, but pirates are the best cheats in all of the seven seas...",
    poster_path: "/uDsvma9dAwnDPVuCFi99YpWvBk0.jpg",
    media_type: "movie",
    genre_ids: [10751, 28, 12],
    popularity: 323.663,
    release_date: "2022-04-20",
    video: false,
    vote_average: 6.792,
    vote_count: 96,
  },
  {
    adult: false,
    backdrop_path: "/daeD5T4MxFk5MppZlaNZoaK6lE9.jpg",
    id: 811948,
    title: "Demon Slayer: Kimetsu no Yaiba the Hashira Meeting Arc",
    original_language: "ja",
    original_title: "鬼滅の刃 柱合会議・蝶屋敷編",
    overview:
      "Tanjiro and his sister Nezuko have been apprehended by the Demon Slayer Hashira, a group of extremely skilled swordfighters. Tanjiro undergoes trial for violating the Demon Slayer code, specifically smuggling Nezuko, a Demon, onto Mt. Natagumo. A recap film of Kimetsu no Yaiba, covering episodes 22-26 with some new footage and special ending credits.",
    poster_path: "/j1FpReEQXp8JsgNQZcfGvzeXNoI.jpg",
    media_type: "movie",
    genre_ids: [16, 14],
    popularity: 210.041,
    release_date: "2021-04-15",
    video: true,
    vote_average: 7.038,
    vote_count: 120,
  },
  {
    adult: false,
    backdrop_path: "/oeBom7DLr85lixEkWOGmhCPEfuY.jpg",
    id: 842942,
    title: "Bandit",
    original_language: "en",
    original_title: "Bandit",
    overview:
      "After escaping a Michigan prison, a charming career criminal assumes a new identity in Canada and goes on to rob a record 59 banks and jewellery stores while being hunted by a rogue task force. Based on the story of The Flying Bandit.",
    poster_path: "/yph9PAbmjYPvyvbeZvdYIhCZHEu.jpg",
    media_type: "movie",
    genre_ids: [80, 18, 53],
    popularity: 132.418,
    release_date: "2022-09-23",
    video: false,
    vote_average: 6.182,
    vote_count: 162,
  },
  {
    adult: false,
    backdrop_path: "/A2avUoNFstnBhAnHiogXQs4c9Bt.jpg",
    id: 772515,
    title: "Huesera: The Bone Woman",
    original_language: "es",
    original_title: "Huesera",
    overview:
      "Valeria's joy at becoming a first-time mother is quickly taken away when she's cursed by a sinister entity. As danger closes in, she's forced deeper into a chilling world of dark magic that threatens to consume her.",
    poster_path: "/zgpj76z9byUgcWnxLDmtZ3XqfvN.jpg",
    media_type: "movie",
    genre_ids: [18, 27, 9648],
    popularity: 109.975,
    release_date: "2023-02-10",
    video: false,
    vote_average: 5.8,
    vote_count: 194,
  },
  {
    adult: false,
    backdrop_path: "/bvAMLx00BOr6vkSQWZscwGrPdGI.jpg",
    id: 1058949,
    title: "Little Dixie",
    original_language: "en",
    original_title: "Little Dixie",
    overview:
      "Erstwhile Special Forces operative Doc Alexander is asked to broker a truce with the Mexican drug cartel in secrecy. When Oklahoma Governor Richard Jeffs celebrates the execution of a high-ranking cartel member on TV, his Chief of Staff and Doc inform him about the peace he just ended. But it’s too late, as Cuco, the cartel’s hatchet man, has set his vengeful sights on Doc’s daughter Dixie.",
    poster_path: "/cmWTZj9zzT9KFt3XyL0gssL7Ig8.jpg",
    media_type: "movie",
    genre_ids: [53, 28, 18, 80],
    popularity: 128.946,
    release_date: "2023-02-03",
    video: false,
    vote_average: 5.884,
    vote_count: 99,
  },
  {
    adult: false,
    backdrop_path: "/cSZLHyKrGIRh3RqMtdYJiD3CinU.jpg",
    id: 1105283,
    title: "My Teacher Ate My Friend",
    original_language: "es",
    original_title: "Mi Maestra se comió a mi amigo",
    overview:
      "Tomás, an 11-year-old boy living in his own fantasy world, must use his vast monster knowledge to fight against his new English teacher: a wicked woman who is, in fact, a child-eating monster.",
    poster_path: "/5MiVG39r82aYUAtvs3bTycmbewJ.jpg",
    media_type: "movie",
    genre_ids: [12, 27, 35, 10751],
    popularity: 52.467,
    release_date: "2023-03-29",
    video: false,
    vote_average: 6.5,
    vote_count: 23,
  },
  {
    adult: false,
    backdrop_path: "/gBHniBVK6JKKquYb9HAnfKy1z1V.jpg",
    id: 938992,
    title: "Pigs Will Be Pigs",
    original_language: "uk",
    original_title: "Свині завжди свині",
    overview:
      'At the "Pupky" station, an opportunity occurs: two illegal passengers - guinea pigs - have to be disembarked from one of the trains, since animals cannot be transported in a general carriage. The head of the station Pryvychkin tries to help the animals, but the situation is beyond his control. The audit committee sets out to investigate the unpleasant incident... This witty satirical comedy, in which bureaucracy, bourgeoisie and provincialism are mocked, continued the development of the domestic comedy genre in Ukrainian Soviet cinema.',
    poster_path: "/b23STDoblAXAsUEZqJjSVePGiwi.jpg",
    media_type: "movie",
    genre_ids: [35],
    popularity: 0.713,
    release_date: "1931-02-10",
    video: false,
    vote_average: 4.5,
    vote_count: 2,
  },
  {
    adult: false,
    backdrop_path: "/pxJbfnMIQQxCrdeLD0zQnWr6ouL.jpg",
    id: 1077280,
    title: "Die Hart",
    original_language: "en",
    original_title: "Die Hart",
    overview:
      "Kevin Hart - playing a version of himself - is on a death-defying quest to become an action star. And with a little help from John Travolta, Nathalie Emmanuel, and Josh Hartnett - he just might pull it off.",
    poster_path: "/1EnBjTJ5utgT1OXYBZ8YwByRCzP.jpg",
    media_type: "movie",
    genre_ids: [28, 35, 53],
    popularity: 178.361,
    release_date: "2023-02-22",
    video: false,
    vote_average: 6.082,
    vote_count: 287,
  },
  {
    adult: false,
    backdrop_path: "/8rpDcsfLJypbO6vREc0547VKqEv.jpg",
    id: 76600,
    title: "Avatar: The Way of Water",
    original_language: "en",
    original_title: "Avatar: The Way of Water",
    overview:
      "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    media_type: "movie",
    genre_ids: [878, 12, 28],
    popularity: 1487.089,
    release_date: "2022-12-14",
    video: false,
    vote_average: 7.703,
    vote_count: 8022,
  },
  {
    adult: false,
    backdrop_path: "/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg",
    id: 677179,
    title: "Creed III",
    original_language: "en",
    original_title: "Creed III",
    overview:
      "After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damian Anderson, resurfaces after serving a long sentence in prison, he is eager to prove that he deserves his shot in the ring. The face-off between former friends is more than just a fight. To settle the score, Adonis must put his future on the line to battle Damian — a fighter who has nothing to lose.",
    poster_path: "/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg",
    media_type: "movie",
    genre_ids: [18, 28],
    popularity: 1080.587,
    release_date: "2023-03-01",
    video: false,
    vote_average: 7.275,
    vote_count: 1364,
  },
  {
    adult: false,
    backdrop_path: "/kRlqWz54iI9K1PjI15cwvtHjnSw.jpg",
    id: 802401,
    title: "Demon Slayer: Kimetsu no Yaiba Mt. Natagumo Arc",
    original_language: "ja",
    original_title: "鬼滅の刃 那田蜘蛛山編",
    overview:
      "Tanjiro, now a registered Demon Slayer, teams up with fellow slayers Zenitsu and Inosuke to investigate missing person cases on the mountain Natagumo. After the group is split up during a fight with possessed swordfighters, they slowly begin to realize the entire mountain is being controlled by a family of Demon spider creatures.  A recap film of Kimetsu no Yaiba, covering episodes 15-21 with some new footage and special ending credits.",
    poster_path: "/wq1UG5lPCKpOJgmgpKJszKvoMUe.jpg",
    media_type: "movie",
    genre_ids: [28, 16, 18, 14, 12],
    popularity: 176.617,
    release_date: "2021-04-15",
    video: true,
    vote_average: 7.9,
    vote_count: 165,
  },
  {
    adult: false,
    backdrop_path: null,
    id: 461191,
    title: "A",
    original_language: "en",
    original_title: "A",
    overview:
      "A young alcoholic ambient musician locks himself in his apartment on a dangerous seven day bender as he attempts to finish his upcoming album.",
    poster_path: "/4uOKZzRB615cIxcVi31pcsdFtSS.jpg",
    media_type: "movie",
    genre_ids: [18, 10402],
    popularity: 2.753,
    release_date: "2017-09-13",
    video: false,
    vote_average: 7.068,
    vote_count: 22,
  },
  {
    adult: false,
    backdrop_path: "/wD2kUCX1Bb6oeIb2uz7kbdfLP6k.jpg",
    id: 980078,
    title: "Winnie the Pooh: Blood and Honey",
    original_language: "en",
    original_title: "Winnie the Pooh: Blood and Honey",
    overview:
      "Christopher Robin is headed off to college and he has abandoned his old friends, Pooh and Piglet, which then leads to the duo embracing their inner monsters.",
    poster_path: "/ewF3IlGscc7FjgGEPcQvZsAsgAW.jpg",
    media_type: "movie",
    genre_ids: [27, 53],
    popularity: 313.847,
    release_date: "2023-01-27",
    video: false,
    vote_average: 5.735,
    vote_count: 585,
  },
];
